apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: quay.io/coreos/hyperkube:v1.3.5_coreos.0
    command:
    - /hyperkube
    - apiserver
    - --bind-address=0.0.0.0
    - --etcd-servers=http://127.0.0.1:2379
    - --allow-privileged=true
    - --service-cluster-ip-range=10.13.0.0/24
    - --advertise-address=159.65.111.31
    - --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota
    - --runtime-config=extensions/v1beta1=true,extensions/v1beta1/networkpolicies=true
    ports:
    - containerPort: 8080
      hostPort: 8080
      name: local
#   volumeMounts:
#   - mountPath: /etc/kubernetes/ssl
#     name: ssl-certs-kubernetes
#     readOnly: true
#   - mountPath: /etc/ssl/certs
#     name: ssl-certs-host
#     readOnly: true
# volumes:
# - hostPath:
#     path: /etc/kubernetes/ssl
#   name: ssl-certs-kubernetes
# - hostPath:
#     path: /usr/share/ca-certificates
#   name: ssl-certs-host
